line-length = 120
indent-width = 4

# Assume Python 3.10
target-version = "py310"

[format]
quote-style = "double"
indent-style = "space"

[lint]
select = ["F", "E", "SIM", "I"]

[lint.isort]
combine-as-imports = true
split-on-trailing-comma = true
