# SYS_ERR values
# section 4.3.59

from typing import NewType


SysErrCode = NewType("SysErrCode", int)

NO_ERROR = SysErrCode(0x00)
PERIPHERAL_INIT_ERROR = SysErrCode(0x01)
SYSTEM_INIT_ERROR = SysErrCode(0x02)
SELF_TEST_FAILED = SysErrCode(0x03)
REGISTER_VALUE_OUT_OF_RANGE = SysErrCode(0x04)
REGISTER_ADDRESS_OUT_OF_RANGE = SysErrCode(0x05)
REGISTER_WRITE_ERROR = SysErrCode(0x06)
LOW_POWER_MODE_UNAVAILABLE = SysErrCode(0x07)
ACCLEROMETER_POWER_MODE_UNAVAILABLE = SysErrCode(0x08)
FUSION_ALGORITHM_CONFGURATION_ERROR = SysErrCode(0x09)
SENSOR_CONFIGURATION_ERROR = SysErrCode(0x0A)
