name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install --editable .[dev]
      - run: python -m mypy rpi_bno055
      - run: python -m ruff check
